services:
  accounts:
    image: "pramithamj/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 7000m
    networks:
      - pramithamj

  loans:
    image: "pramithamj/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 7000m
    networks:
      - pramithamj

  cards:
    image: "pramithamj/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 7000m
    networks:
      - pramithamj
networks:
  pramithamj:
    driver: "bridge"